---
version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
report_sizes: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}"

builds:
# Used by homebrew
- env:
  - CGO_ENABLED=0
  id: "aws-sso"
  binary: "aws-sso"
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - "amd64"
  - "arm"
  - "arm64"
  - "386"
  ignore:
  - goos: windows
    goarch: arm
  ldflags:
  - -s -w -X 'github.com/louislef299/aws-sso/pkg/version.Version={{.Version}}'
  - -X 'github.com/louislef299/aws-sso/pkg/version.BuildOS={{.Env.GOOS}}'
  - -X 'github.com/louislef299/aws-sso/pkg/version.BuildArch={{.Env.GOARCH}}'
  - -X 'github.com/louislef299/aws-sso/pkg/version.GoVersion={{.Env.GOVERSION}}'
  - -X 'github.com/louislef299/aws-sso/pkg/version.BuildTime={{.Date}}'
  - -X 'github.com/louislef299/aws-sso/pkg/version.CommitHash={{.ShortCommit}}'
  
# Used by krew
- env:
  - CGO_ENABLED=0
  id: "kubectl-aws_sso"
  binary: "kubectl-aws_sso"
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - "amd64"
  - "arm"
  - "arm64"
  - "386"
  ignore:
  - goos: windows
    goarch: arm
  flags:
  - -tags=kube
  ldflags:
  - -s -w -X 'github.com/louislef299/aws-sso/pkg/version.Version={{.Version}}'
  - -X 'github.com/louislef299/aws-sso/pkg/version.BuildOS={{.Runtime.Goos}}'
  - -X 'github.com/louislef299/aws-sso/pkg/version.BuildArch={{.Runtime.Goarch}}'
  - -X 'github.com/louislef299/aws-sso/pkg/version.GoVersion={{.Env.GOVERSION}}'
  - -X 'github.com/louislef299/aws-sso/pkg/version.BuildTime={{.Date}}'
  - -X 'github.com/louislef299/aws-sso/pkg/version.CommitHash={{.ShortCommit}}'

archives:
- ids:
  - aws-sso
  - brew-sig
  id: aws-sso
  files:
  - LICENSE
  - src: dist/{{.ProjectName}}_{{.Os}}_{{.Arch}}*/*.sig
    strip_parent: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
- ids:
  - kubectl-aws_sso
  - krew-sig
  id: kubectl-aws_sso
  files:
  - LICENSE
  - src: dist/kubectl*{{.Os}}*{{.Arch}}*/*.sig
    strip_parent: true
  name_template: "kubectl-{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

binary_signs:
- id: brew-sig
  cmd: gpg
  artifacts: binary
  signature: "${artifact}_{{ .Os }}_{{ .Arch }}.sig"
  args: ["-u", "{{.Env.GPG_SIGNING_KEY}}", "--output", "${signature}", "--detach-sign", "${artifact}"]
  ids:
  - aws-sso
  output: false
- id: krew-sig
  cmd: gpg
  artifacts: binary
  signature: "${artifact}_{{ .Os }}_{{ .Arch }}.sig"
  args: ["-u", "{{.Env.GPG_SIGNING_KEY}}", "--output", "${signature}", "--detach-sign", "${artifact}"]
  ids:
  - kubectl-aws_sso
  output: false

homebrew_casks:
- name: aws-sso
  description: >-
    Thanks for installing aws-sso! You can get configured by going to
    https://aws-sso.netlify.app. The binary you have installed came with
    a binary signature if you would like to verify the install. More
    information can be found on the website
  commit_author:
    name: Louis Lefebvre
    email: louislefebvre1999@gmail.com
    signing:
      enabled: true
      key: "{{ .Env.GPG_SIGNING_KEY }}"
      program: gpg
      format: openpgp
  commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://github.com/louislef299/aws-sso"
  ids: 
  - aws-sso
  repository:
    owner: louislef299
    name: homebrew-aws-sso
    branch: main
    token: "{{ .Env.GITHUB_TOKEN }}"
  hooks:
    post:
      install: |
        if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
          system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-sso"]
        end

krews:
- name: aws-sso
  ids:
  - kubectl-aws_sso
  commit_author:
    name: Louis Lefebvre
    email: louislefebvre1999@gmail.com
    signing:
      enabled: true
      key: "{{ .Env.GPG_SIGNING_KEY }}"
      program: gpg
      format: openpgp
  commit_msg_template: "chore: Krew plugin update for {{ .ProjectName }} version {{ .Tag }}"
  description: "A simplified AWS SSO manager to make authenticating to EKS and ECR easier."
  short_description: "A simplified AWS SSO manager."
  repository:
      owner: louislef299
      name: aws-sso
      branch: release-krew
      pull_request:
        enabled: true
