---
name: Scan Vulnerabilities
on:
  pull_request:
    branches: 
    - "main"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  trivy-vuln-scan:
    name: Trivy Scan Filesystem Vulnerabilities
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Trivy Security Scan
      uses: aquasecurity/trivy-action@0.32.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        hide-progress: false
        format: 'table'
        exit-code: '1'
        severity: 'MEDIUM,HIGH,CRITICAL'
        scanners: vuln,secret

  trivy-compliance:
    name: Trivy Scan Licenses
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Trivy License Security Scan
      uses: aquasecurity/trivy-action@0.32.0
      env:
        TRIVY_LICENSE_FULL: true
      with:
        scan-type: 'fs'
        scan-ref: '.'
        hide-progress: false
        format: 'table'
        exit-code: '1'
        severity: 'HIGH,CRITICAL'
        scanners: license
        trivy-config: './trivy.yaml'
